---
- hosts: all
  user: root
  tasks:
    - name: install xinetd
      yum: pkg=$item state=latest
      with_items:
        - xinetd
    - name: config xinetd
      template: src=/home/ansible/copy_files/xinetd.j2 dest=/etc/xinetd.d/check_mk
    - name: copy check_mk agent
      copy: src=/home/ansible/copy_files/check_mk-agent-1.2.2p2-1.noarch.rpm dest=/tmp
    - name: copy check_mk logwatch
      copy: src=/home/ansible/copy_files/check_mk-agent-logwatch-1.2.2p2-1.noarch.rpm dest=/tmp
    - name: Install Check_Mk
      command: /bin/rpm -ivh /tmp/check_mk-agent*
      notify:
      - restart xinetd
    - name: ensure xinetd is running
      service: name=xinetd state=started
  handlers:
    - name: restart xinetd
      service: name=xinetd state=restarted
